// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Tlaoami.Infrastructure.Migrations
{
    [DbContext(typeof(TlaoamiDbContext))]
    [Migration("20260120225545_AddSalones")]
    partial class AddSalones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tlaoami.Domain.Entities.AceptacionAvisoPrivacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AceptadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AvisoPrivacidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvisoPrivacidadId");

                    b.HasIndex("UsuarioId", "AvisoPrivacidadId")
                        .IsUnique();

                    b.ToTable("AceptacionesAvisoPrivacidad");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_AlumnoId_Activo");

                    b.HasIndex("GrupoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_GrupoId_Activo");

                    b.ToTable("AsignacionesGrupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AvisoPrivacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublicadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Vigente")
                        .IsUnique()
                        .HasFilter("Vigente = true");

                    b.ToTable("AvisosPrivacidad");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CiclosEscolares");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ConceptoCobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Periodicidad")
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCFDI")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConceptosCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CicloEscolarId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid?>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Turno")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("SalonId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoBancario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashMovimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashMovimiento")
                        .IsUnique();

                    b.ToTable("MovimientosBancarios");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaConciliacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovimientoBancarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MovimientoBancarioId");

                    b.ToTable("MovimientosConciliacion");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PaymentIntentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique()
                        .HasFilter("\"PaymentIntentId\" IS NOT NULL");

                    b.HasIndex("FacturaId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClabeDestino")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiraEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Proveedor")
                        .HasColumnType("text");

                    b.Property<string>("ProveedorReferencia")
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaSpei")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaCobroPorCiclo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiaCorte")
                        .HasColumnType("integer");

                    b.Property<int?>("Grado")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TipoGeneracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("CicloId", "Grado", "Turno", "ConceptoCobroId", "TipoGeneracion")
                        .IsUnique()
                        .HasDatabaseName("IX_ReglasCobro_Unique_Logico");

                    b.ToTable("ReglasCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Reinscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CicloDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CicloOrigenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GrupoDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoOrigenId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SaldoAlMomento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicloDestinoId");

                    b.HasIndex("CicloOrigenId");

                    b.HasIndex("GrupoDestinoId");

                    b.HasIndex("GrupoOrigenId");

                    b.HasIndex("AlumnoId", "CicloDestinoId")
                        .IsUnique();

                    b.ToTable("Reinscripciones");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Salon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Salones");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AceptacionAvisoPrivacidad", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.AvisoPrivacidad", "AvisoPrivacidad")
                        .WithMany("Aceptaciones")
                        .HasForeignKey("AvisoPrivacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvisoPrivacidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("AsignacionesGrupo")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Facturas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany("Grupos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CicloEscolar");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tlaoami.Domain.Entities.MovimientoBancario", "MovimientoBancario")
                        .WithMany()
                        .HasForeignKey("MovimientoBancarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Factura");

                    b.Navigation("MovimientoBancario");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", null)
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaCobroPorCiclo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Reinscripcion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloDestino")
                        .WithMany()
                        .HasForeignKey("CicloDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloOrigen")
                        .WithMany()
                        .HasForeignKey("CicloOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "GrupoDestino")
                        .WithMany()
                        .HasForeignKey("GrupoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "GrupoOrigen")
                        .WithMany()
                        .HasForeignKey("GrupoOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("CicloDestino");

                    b.Navigation("CicloOrigen");

                    b.Navigation("GrupoDestino");

                    b.Navigation("GrupoOrigen");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("AsignacionesGrupo");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AvisoPrivacidad", b =>
                {
                    b.Navigation("Aceptaciones");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
