// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Tlaoami.Infrastructure.Migrations
{
    [DbContext(typeof(TlaoamiDbContext))]
    [Migration("20260128012927_ExpandEscuelaSettingsWithInstitutionalInfo")]
    partial class ExpandEscuelaSettingsWithInstitutionalInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tlaoami.Domain.Entities.AceptacionAvisoPrivacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AceptadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AvisoPrivacidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvisoPrivacidadId");

                    b.HasIndex("UsuarioId", "AvisoPrivacidadId")
                        .IsUnique();

                    b.ToTable("AceptacionesAvisoPrivacidad");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoAsignacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoOverride")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId1");

                    b.HasIndex("CicloId");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("AlumnoId", "Activo");

                    b.HasIndex("AlumnoId", "CicloId");

                    b.ToTable("AlumnoAsignaciones", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_AlumnoId_Activo");

                    b.HasIndex("GrupoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_GrupoId_Activo");

                    b.ToTable("AsignacionesGrupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AvisoPrivacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublicadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Vigente")
                        .IsUnique()
                        .HasFilter("Vigente = true");

                    b.ToTable("AvisosPrivacidad");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.BecaAlumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicloId");

                    b.HasIndex("AlumnoId", "CicloId")
                        .IsUnique();

                    b.ToTable("BecasAlumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CiclosEscolares");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ConceptoCobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaRecargo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Periodicidad")
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCFDI")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoConcepto")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConceptosCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ConciliacionMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfirmadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MovimientoBancarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PagoReportadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReglaMatch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoBancarioId")
                        .HasDatabaseName("IX_ConciliacionMatches_MovimientoBancarioId");

                    b.HasIndex("PagoReportadoId")
                        .HasDatabaseName("IX_ConciliacionMatches_PagoReportadoId");

                    b.HasIndex("AlumnoId", "Estatus")
                        .HasDatabaseName("IX_ConciliacionMatches_AlumnoId_Estatus");

                    b.HasIndex("MovimientoBancarioId", "Estatus")
                        .IsUnique()
                        .HasDatabaseName("IX_ConciliacionMatches_MovimientoBancarioId_Confirmado_Unique")
                        .HasFilter("\"Estatus\" = 1");

                    b.ToTable("ConciliacionMatches", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CuentaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Clabe")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ultimos4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId", "Activa")
                        .HasDatabaseName("IX_CuentasBancarias_EscuelaId_Activa");

                    b.ToTable("CuentasBancarias", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.EscuelaSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BloquearReinscripcionConSaldo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaCorteColegiatura")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TextoRecibos")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId")
                        .IsUnique();

                    b.ToTable("EscuelaSettings", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrigenId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OrigenTipo")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("ReciboEmitidoAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReciboFolio")
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("AlumnoId", "Periodo", "ConceptoCobroId")
                        .IsUnique()
                        .HasDatabaseName("IX_Factura_Alumno_Periodo_Concepto")
                        .HasFilter("\"Estado\" <> 'Cancelada'");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.FacturaFiscal", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CfdiPdfBase64")
                        .HasColumnType("text");

                    b.Property<string>("CfdiUuid")
                        .HasColumnType("text");

                    b.Property<string>("CfdiXmlBase64")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorTimbrado")
                        .HasColumnType("text");

                    b.Property<string>("EstadoTimbrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceptorCodigoPostalSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ReceptorNombreSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ReceptorRegimenSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("ReceptorRfcSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimbradoAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsoCfdi")
                        .HasColumnType("text");

                    b.HasKey("FacturaId");

                    b.HasIndex("CfdiUuid")
                        .IsUnique();

                    b.ToTable("FacturasFiscales");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.FacturaLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Impuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("FacturaId", "ConceptoCobroId");

                    b.ToTable("FacturaLineas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("CicloEscolarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DocenteTitularId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid?>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Seccion")
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("DocenteTitularId");

                    b.HasIndex("SalonId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ImportBancarioBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuentaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PeriodoFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodoInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAbonos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCargos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMovimientos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaId")
                        .HasDatabaseName("IX_ImportBatches_CuentaBancariaId");

                    b.HasIndex("EscuelaId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ImportBatches_EscuelaId_CreatedAtUtc");

                    b.ToTable("ImportBancarioBatches", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoBancario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashUnico")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ReferenciaBanco")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("HashUnico")
                        .IsUnique()
                        .HasDatabaseName("IX_MovimientosBancarios_HashUnico_Unique")
                        .HasFilter("\"HashUnico\" IS NOT NULL");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_MovimientosBancarios_ImportBatchId");

                    b.HasIndex("EscuelaId", "Estado")
                        .HasDatabaseName("IX_MovimientosBancarios_EscuelaId_Estado");

                    b.HasIndex("Fecha", "Monto")
                        .HasDatabaseName("IX_MovimientosBancarios_FechaMovimiento_Monto");

                    b.ToTable("MovimientosBancarios", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaConciliacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovimientoBancarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MovimientoBancarioId");

                    b.ToTable("MovimientosConciliacion");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.OrdenVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmadaAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AlumnoId1");

                    b.HasIndex("Estatus");

                    b.HasIndex("Fecha");

                    b.ToTable("OrdenesVenta", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.OrdenVentaLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrdenVentaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenVentaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesVentaLineas", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PaymentIntentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PaymentIntentId")
                        .IsUnique()
                        .HasFilter("\"PaymentIntentId\" IS NOT NULL");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PagoReportado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EscuelaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaReportada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoReportado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReferenciaTexto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FechaReportada")
                        .HasDatabaseName("IX_PagosReportados_FechaReportada");

                    b.HasIndex("AlumnoId", "Estatus")
                        .HasDatabaseName("IX_PagosReportados_AlumnoId_Estatus");

                    b.HasIndex("MontoReportado", "FechaReportada")
                        .HasDatabaseName("IX_PagosReportados_MontoReportado_FechaReportada");

                    b.ToTable("PagosReportados", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClabeDestino")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiraEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Proveedor")
                        .HasColumnType("text");

                    b.Property<string>("ProveedorReferencia")
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaSpei")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReceptorFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPostalFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NombreFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsoCfdiDefault")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .IsUnique();

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("ReceptoresFiscales");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaCobroPorCiclo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiaCorte")
                        .HasColumnType("integer");

                    b.Property<int?>("Grado")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TipoGeneracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("CicloId", "Grado", "Turno", "ConceptoCobroId", "TipoGeneracion")
                        .IsUnique()
                        .HasDatabaseName("IX_ReglasCobro_Unique_Logico");

                    b.ToTable("ReglasCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaColegiatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaVencimiento")
                        .HasColumnType("integer");

                    b.Property<int?>("Grado")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("CicloId", "GrupoId", "Grado", "Turno", "ConceptoCobroId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReglaColegiatura_Unique");

                    b.ToTable("ReglasColegiatura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaRecargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptoCobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiasGracia")
                        .HasColumnType("integer");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CicloId")
                        .IsUnique();

                    b.HasIndex("ConceptoCobroId");

                    b.ToTable("ReglasRecargo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Reinscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CicloDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CicloOrigenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GrupoDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoOrigenId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SaldoAlMomento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicloDestinoId");

                    b.HasIndex("CicloOrigenId");

                    b.HasIndex("GrupoDestinoId");

                    b.HasIndex("GrupoOrigenId");

                    b.HasIndex("AlumnoId", "CicloDestinoId")
                        .IsUnique();

                    b.ToTable("Reinscripciones");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Salon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Salones", (string)null);
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AceptacionAvisoPrivacidad", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.AvisoPrivacidad", "AvisoPrivacidad")
                        .WithMany("Aceptaciones")
                        .HasForeignKey("AvisoPrivacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvisoPrivacidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoAsignacion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Alumno", null)
                        .WithMany("AsignacionesCobro")
                        .HasForeignKey("AlumnoId1");

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("AsignacionesGrupo")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.BecaAlumno", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "Ciclo")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Ciclo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ConciliacionMatch", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("ConciliacionMatches")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.MovimientoBancario", "MovimientoBancario")
                        .WithMany("Matches")
                        .HasForeignKey("MovimientoBancarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.PagoReportado", "PagoReportado")
                        .WithMany("Matches")
                        .HasForeignKey("PagoReportadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("MovimientoBancario");

                    b.Navigation("PagoReportado");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Facturas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.FacturaFiscal", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithOne("FacturaFiscal")
                        .HasForeignKey("Tlaoami.Domain.Entities.FacturaFiscal", "FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.FacturaLinea", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptoCobro");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany("Grupos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.User", "DocenteTitular")
                        .WithMany()
                        .HasForeignKey("DocenteTitularId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CicloEscolar");

                    b.Navigation("DocenteTitular");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ImportBancarioBatch", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CuentaBancaria", "CuentaBancaria")
                        .WithMany("ImportBatches")
                        .HasForeignKey("CuentaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaBancaria");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoBancario", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CuentaBancaria", "CuentaBancaria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaBancariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.ImportBancarioBatch", "ImportBatch")
                        .WithMany("Movimientos")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CuentaBancaria");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId");

                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId");

                    b.HasOne("Tlaoami.Domain.Entities.MovimientoBancario", "MovimientoBancario")
                        .WithMany()
                        .HasForeignKey("MovimientoBancarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Factura");

                    b.Navigation("MovimientoBancario");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.OrdenVenta", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Alumno", null)
                        .WithMany("OrdenesVenta")
                        .HasForeignKey("AlumnoId1");

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.OrdenVentaLinea", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.OrdenVenta", "OrdenVenta")
                        .WithMany("Lineas")
                        .HasForeignKey("OrdenVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenVenta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PagoReportado", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("PagosReportados")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", null)
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReceptorFiscal", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithOne("ReceptorFiscal")
                        .HasForeignKey("Tlaoami.Domain.Entities.ReceptorFiscal", "AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaCobroPorCiclo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaColegiatura", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ReglaRecargo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.ConceptoCobro", "ConceptoCobro")
                        .WithMany()
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Reinscripcion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloDestino")
                        .WithMany()
                        .HasForeignKey("CicloDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloOrigen")
                        .WithMany()
                        .HasForeignKey("CicloOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "GrupoDestino")
                        .WithMany()
                        .HasForeignKey("GrupoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "GrupoOrigen")
                        .WithMany()
                        .HasForeignKey("GrupoOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("CicloDestino");

                    b.Navigation("CicloOrigen");

                    b.Navigation("GrupoDestino");

                    b.Navigation("GrupoOrigen");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("AsignacionesCobro");

                    b.Navigation("AsignacionesGrupo");

                    b.Navigation("ConciliacionMatches");

                    b.Navigation("Facturas");

                    b.Navigation("OrdenesVenta");

                    b.Navigation("PagosReportados");

                    b.Navigation("ReceptorFiscal");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AvisoPrivacidad", b =>
                {
                    b.Navigation("Aceptaciones");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CuentaBancaria", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Navigation("FacturaFiscal");

                    b.Navigation("Lineas");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.ImportBancarioBatch", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoBancario", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.OrdenVenta", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PagoReportado", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
