// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tlaoami.Infrastructure.Migrations
{
    [DbContext(typeof(TlaoamiDbContext))]
    [Migration("20260119062101_AddAlumnosGruposCiclos")]
    partial class AddAlumnosGruposCiclos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_AlumnoId_Activo");

                    b.HasIndex("GrupoId", "Activo")
                        .HasDatabaseName("IX_AlumnoGrupo_GrupoId_Activo");

                    b.ToTable("AsignacionesGrupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CiclosEscolares");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CicloEscolarId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Turno")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoBancario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashMovimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashMovimiento")
                        .IsUnique();

                    b.ToTable("MovimientosBancarios");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaConciliacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovimientoBancarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MovimientoBancarioId");

                    b.ToTable("MovimientosConciliacion");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentIntentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique()
                        .HasFilter("[PaymentIntentId] IS NOT NULL");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualizadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClabeDestino")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiraEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProveedorReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaSpei")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.AlumnoGrupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("AsignacionesGrupo")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tlaoami.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Facturas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.CicloEscolar", "CicloEscolar")
                        .WithMany("Grupos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CicloEscolar");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.MovimientoConciliacion", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tlaoami.Domain.Entities.MovimientoBancario", "MovimientoBancario")
                        .WithMany()
                        .HasForeignKey("MovimientoBancarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Factura");

                    b.Navigation("MovimientoBancario");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.PaymentIntent", b =>
                {
                    b.HasOne("Tlaoami.Domain.Entities.Factura", null)
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("AsignacionesGrupo");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.CicloEscolar", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Tlaoami.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
